<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.geek_blogbundle_command_createusercommand_create_user.command' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Geek/BlogBundle/Command/CreateUserCommand.php';

return $this->services['console.command.geek_blogbundle_command_createusercommand_create_user.command'] = new \Geek\BlogBundle\Command\CreateUserCommand(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, ${($_ = isset($this->services['security.password_encoder']) ? $this->services['security.password_encoder'] : $this->load(__DIR__.'/getSecurity_PasswordEncoderService.php')) && false ?: '_'});
