security:

    encoders:
        Geek\BlogBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        our_db_provider:
            entity:
                class:  GeekBlogBundle:User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login_check
                username_parameter: username
                password_parameter: password
                always_use_default_target_path: true
                default_target_path: /redirect
            logout:
                path: logout
            logout_on_user_change: true

    access_control:
          - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
          - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
          - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY}
          - { path: ^/user, roles: IS_AUTHENTICATED_FULLY}
          - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY}
