<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Geek\BlogBundle\Form\NewUserType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Geek/BlogBundle/Form/NewUserType.php';

return $this->services['Geek\BlogBundle\Form\NewUserType'] = new \Geek\BlogBundle\Form\NewUserType();
