<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.main_menu' shared autowired service.

include_once $this->targetDirs[3].'/src/Geek/BlogBundle/Menu/Builder.php';
include_once $this->targetDirs[3].'/vendor/knplabs/knp-menu/src/Knp/Menu/ItemInterface.php';
include_once $this->targetDirs[3].'/vendor/knplabs/knp-menu/src/Knp/Menu/MenuItem.php';

return $this->services['app.main_menu'] = (new \Geek\BlogBundle\Menu\Builder(${($_ = isset($this->services['knp_menu.factory']) ? $this->services['knp_menu.factory'] : $this->load(__DIR__.'/getKnpMenu_FactoryService.php')) && false ?: '_'}))->createMainMenu(${($_ = isset($this->services['request_stack']) ? $this->services['request_stack'] : $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()) && false ?: '_'});
