<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'knp_menu.templating.helper' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Templating/Helper/HelperInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Templating/Helper/Helper.php';
include_once $this->targetDirs[3].'/vendor/knplabs/knp-menu-bundle/src/Templating/Helper/MenuHelper.php';

return $this->services['knp_menu.templating.helper'] = new \Knp\Bundle\MenuBundle\Templating\Helper\MenuHelper(${($_ = isset($this->services['knp_menu.helper']) ? $this->services['knp_menu.helper'] : $this->getKnpMenu_HelperService()) && false ?: '_'}, ${($_ = isset($this->services['knp_menu.matcher']) ? $this->services['knp_menu.matcher'] : $this->getKnpMenu_MatcherService()) && false ?: '_'}, ${($_ = isset($this->services['knp_menu.manipulator']) ? $this->services['knp_menu.manipulator'] : $this->services['knp_menu.manipulator'] = new \Knp\Menu\Util\MenuManipulator()) && false ?: '_'});
