<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIwnaypf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIwnaypf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIwnaypf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIwnaypf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIwnaypf\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Iwnaypf',
    'container.build_id' => '6fb91f30',
    'container.build_time' => 1518736847,
));
