<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4mxbst5\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4mxbst5/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4mxbst5.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4mxbst5\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4mxbst5\appDevDebugProjectContainer(array(
    'container.build_hash' => '4mxbst5',
    'container.build_id' => 'ec398073',
    'container.build_time' => 1522380672,
));
