<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX5cpgug\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX5cpgug/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX5cpgug.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX5cpgug\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerX5cpgug\appDevDebugProjectContainer(array(
    'container.build_hash' => 'X5cpgug',
    'container.build_id' => 'c05f2811',
    'container.build_time' => 1519938298,
));
